### ISSUE TITLE
Registreren

### ISSUE THREAD

**Issue by norakramer1** [LarsHVA/Challenger#2]
Binnen het team project gaat Deiver zich bezig houden met het registreer feature daarvoor moet er een:
* [x] registreer formulier aangemaakt zijn
* [x] met een registreer pagina
* [x] multer package installeren zodat je een afbeelding kan uploaden
* [x] eigen code injecteren
* [x] API injecteren voor game name

**Comment by deinca** [comment]
Voorbeeld dat het gelukt is om de code van mijn feature toe te passen in dit team project:
**Afbeeldingen kunnen uploaden**
<img width="50%" alt="Schermafbeelding 2021-03-16 om 21 44 48" src="https://user-images.githubusercontent.com/44967374/112565769-fdc88d80-8ddd-11eb-9479-0eb0f42056cc.png">

**Comment by deinca** [comment]
### Voorbeeld dat het gelukt is om de API  van IGDB game namen toe te voegen in de registratie pagina:

![image](https://user-images.githubusercontent.com/44967374/112565953-63b51500-8dde-11eb-9c2e-8e4a4a5c4a3f.png)

**Comment by deinca** [comment]
De laatste stap voor het weergeven van de API cover games toegepast:
![image](https://user-images.githubusercontent.com/44967374/112717585-1627cd80-8eee-11eb-9e99-ac543ccbe7f2.png)

**Comment by deinca** [comment]
- [x] Game covers toegepast in de match pagina
- [x] Game namen zijn toegvoegd met Client JS
